# Generated by Django 5.0.4 on 2024-04-25 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_userprofile_province_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("starts", models.DateTimeField()),
                ("ends", models.DateTimeField()),
                (
                    "attendance",
                    models.CharField(
                        choices=[("I", "InPerson"), ("O", "Online")], max_length=1
                    ),
                ),
                ("maximum_tickets", models.IntegerField()),
                ("registered_tickets", models.IntegerField(default=0)),
                ("is_paid", models.BooleanField(default=False)),
                (
                    "ticket_price",
                    models.DecimalField(decimal_places=2, max_digits=6, null=True),
                ),
                ("organizer_phone", models.CharField(max_length=11)),
                ("organizer_SSN", models.CharField(max_length=11)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InPersonEvent",
            fields=[
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="data.event",
                    ),
                ),
                ("province", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("location_lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("location_lon", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="OnlineEvent",
            fields=[
                (
                    "event",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="data.event",
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="TaggedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.event"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.tag"
                    ),
                ),
            ],
        ),
    ]
