# Generated by Django 5.0.3 on 2024-03-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_attendeeprofile_id_attendeeprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeprofile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
