# Generated by Django 5.0.4 on 2024-04-28 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_remove_eventtag_event_eventtag_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventtag",
            name="event",
        ),
        migrations.AddField(
            model_name="eventtag",
            name="event",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="data.event"
            ),
            preserve_default=False,
        ),
    ]
