# Generated by Django 5.0.4 on 2024-05-07 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_remove_eventtag_event_eventtag_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="balance",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="ssn",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
