# Generated by Django 5.0.4 on 2024-05-17 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_remove_eventtag_event_eventtag_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarked_events',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_registered',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registered_events',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wallet',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
