# Generated by Django 5.0.4 on 2024-05-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_userprofile_balance_userprofile_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventtag",
            old_name="tag",
            new_name="label",
        ),
        migrations.RemoveField(
            model_name="eventtag",
            name="event",
        ),
        migrations.AddField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(to="data.eventtag"),
        ),
    ]
