# Generated by Django 5.0.4 on 2024-05-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0008_rename_tag_eventtag_label_remove_eventtag_event_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EventTag",
            new_name="Tag",
        ),
    ]
