# Generated by Django 5.0.4 on 2024-05-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_alter_event_ticket_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inpersonevent",
            name="location_lat",
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
        migrations.AlterField(
            model_name="inpersonevent",
            name="location_lon",
            field=models.DecimalField(decimal_places=10, max_digits=12),
        ),
    ]
