# Generated by Django 5.0.4 on 2024-05-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0011_alter_inpersonevent_location_lat_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ticket_price",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="inpersonevent",
            name="location_lat",
            field=models.DecimalField(decimal_places=15, max_digits=17),
        ),
        migrations.AlterField(
            model_name="inpersonevent",
            name="location_lon",
            field=models.DecimalField(decimal_places=15, max_digits=18),
        ),
    ]
