# Generated by Django 5.0.4 on 2024-05-13 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="replies",
        ),
        migrations.AddField(
            model_name="comment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="data.comment",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="data.event",
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="score",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
