# Generated by Django 5.0.4 on 2024-05-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0016_comment_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarked_events',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_registered',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registered_events',
            field=models.JSONField(null=True),
        ),
    ]
