# Generated by Django 5.0.4 on 2024-05-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_notification"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="time",
            new_name="created_at",
        ),
    ]
