# Generated by Django 5.0.4 on 2024-06-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0018_rename_time_notification_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_enrolled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendee_name", models.CharField(max_length=255)),
                ("attendee_email", models.EmailField(max_length=254)),
                ("attendee_phone", models.CharField(max_length=15)),
                ("price", models.IntegerField()),
                (
                    "attendee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.userprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.event"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="enrolled_events",
            field=models.ManyToManyField(through="data.Ticket", to="data.event"),
        ),
    ]
