# Generated by Django 5.0.4 on 2024-06-30 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0020_conversation_message_userconversation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_history",
                to="data.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="conversations",
            field=models.ManyToManyField(
                related_name="participants",
                through="data.UserConversation",
                to="data.conversation",
            ),
        ),
    ]
