# Generated by Django 5.0.4 on 2024-07-03 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0023_remove_message_recipient_remove_user_contacts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="conversations",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="conversations",
            field=models.ManyToManyField(
                related_name="participants",
                through="data.UserConversation",
                to="data.conversation",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="data.userprofile"
            ),
        ),
        migrations.AlterField(
            model_name="userconversation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="data.userprofile"
            ),
        ),
    ]
