# Generated by Django 5.0.4 on 2024-07-05 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_remove_user_conversations_userprofile_conversations_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventBookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.userprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="bookmarked_events",
            field=models.ManyToManyField(
                related_name="bookmarked_by",
                through="data.EventBookmark",
                to="data.event",
            ),
        ),
    ]
